name: angular application for S3 Deploy
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AKIAX63XDOBLQCMEHSXO }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.'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' }}
      AWS_DEFAULT_REGION: ${{ secrets.N.Virginia }}
    steps:
        - uses: actions/checkout@main

        - name: Install dependencies
          run: yarn

        - name: Build
          run: yarn build

        - name: Deploy
          uses: lbertenasco/s3-deploy@main
          with:
            folder: build
            bucket: ${{ secrets.machinetest.zehntech.net }}
            dist-id: ${{ secrets.E8TZ0S553QKZD }}
            invalidation: / *
